Repository spacetelescope/mirage, pull requests merged in 2019-06, with the labels that each got.

#305 Fix Travis and environment file; Update README
  .travis.yml
  README.md
  docs/install.rst
  environment.yml
  mirage_environment_linux.yml
  mirage_environment_osx.yml
  setup.py
  tests/test_apt.py
  tests/test_apt_interface.py
  tests/test_catalog_generation.py
  tests/test_fgs_imaging.py
  tests/test_nircam_imaging.py
  tests/test_niriss_imaging.py
  tests/test_niriss_imaging_modes.py
  tests/test_psf_library.py
  tests/test_spectra_from_catalog.py
Labels: Bug, Documentation, Enhancement, Testing

#296 Implement FGS1 and FGS2 magnitudes.
  mirage/catalogs/catalog_generator.py
  mirage/seed_image/catalog_seed_image.py
Labels: Enhancement

#273 AMI simulations tests
  .gitignore
  examples/niriss_ami_example/input_files/793_mirage_example.pointing
  examples/niriss_ami_example/input_files/793_mirage_example.xml
  examples/niriss_ami_example/niriss_ami_example.py
  examples/niriss_ami_example/stars_field19_20_combined_allfilters.list
  mirage/apt/read_apt_xml.py
  mirage/seed_image/catalog_seed_image.py
  mirage/yaml/yaml_generator.py
  tests/test_apt_interface.py
  tests/test_data/NIRISS/com1093.pointing
  tests/test_data/NIRISS/com1093.xml
Labels: Enhancement, Medium Priority

#317 PSF selection for NIRISS NRM imaging
  mirage/psf/psf_selection.py
Labels: Bug, Enhancement
